### PR TITLE
Rename NuGet.CommandLine to NuGet.CommandLine.XPlat to avoid name conflict with the other NuGet.CommandLine.

### PR DESCRIPTION
**Pull request by feiling**
Just simple directory and namespace renaming.

@emgarten @deepakaravindr @zhili1208 @yishaigalatzer

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
:shipit:

**Comment by feiling** [comment]
rebased and merged.

**Pull request closed without merging**
