### PR TITLE
Add Xamarin.WatchOS framework

### PR DESCRIPTION
**Pull request by mrward**
This adds a new Xamarin.WatchOS target framework to NuGet 3.

There is also a [pull request](https://nuget.codeplex.com/SourceControl/network/forks/MattWard/mononuget/contribution/8405) on CodePlex to add the new target framework to NuGet 2.8.8.

### CODE REVIEW

**Comment by mrward** [comment]
I have opened a [pull request](https://github.com/NuGet/NuGet.V2/pull/2) on GitHub for NuGet v2 since CodePlex is no longer being used.

**Comment by emgarten** [comment]
@mrward when will Xamarin with Xamarin.WatchOS be released?

**Comment by mrward** [comment]
@emgarten - The plan is to release it when the final version of iOS 9 is released. That date depends on Apple and is currently unknown. Based on reading online news reports this may be sometime in September.

**Comment by zhili1208** [comment]
ported to NuGet.Client and merged it

**Pull request closed without merging**
