### PR TITLE
fix NuGet/Home#622 by correctly handling a locked lockfile

### LINKED ISSUE #622: Read the lock file in Restore and check for locked:true
If the lock file exists and contains "locked: true", it should be used to constrain the packages that are restored. This code needs to be added to `RestoreCommand`.

### PR DESCRIPTION
**Pull request by analogrelay**
fixes NuGet/Home#622

To test it out:
1. Clone this repo (if you don't already have it)
2. `git checkout anurse/622-lock-dat-file`
3. `.\build`
4. `cd misc\RestoreTests\LockedLockFile`
5. Clear your `%USERPROFILE%\.nuget\packages` directory
6. Run `..\..\..\nuget3 restore --source https://www.myget.org/F/dotnet-core/api/v2`

The expected result is that, **despite** the `*` in project.json and the fact that there are higher versions on the feed, only versions `4.0.x-beta-22927` are restored.

/cc @davidfowl @lodejard @ericstj @emgarten @yishaigalatzer

### CODE REVIEW

**Comment by analogrelay** [comment]
Heh, of course my testing instructions would only work if I checked in the lock file :P. Stand by for update.

**Comment by analogrelay** [comment]
Fixed and also added lock file validation (ping @davidfowl)

**Comment by emgarten** [comment]
unit tests!

**Comment by analogrelay** [comment]
Well, we don't really have any unit tests for this at all, but I'll try to bash up a functional test :)

**Comment by analogrelay** [comment]
Done. Should have addressed everything except what to do with an out-of-date locked lock file. That's still a discussion point.

**Comment by emgarten** [comment]
:shipit: :rocket:

**Comment by analogrelay** [comment]
:earth_americas: :rocket: :crescent_moon: :us: :rocket: :earth_americas: :ocean: :boat: :car: :confetti_ball: :tada: !

Merging now ;)

**Pull request merged**
