### PR TITLE
Fall back to runtime-agnostic native folder if package doesn't have a runtime-specific native folder

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes NuGet/Home#1454

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
Hey

1st please let us triage the bug and make a decision if we want this suggested fix or not :)

Second we are moving out of NuGet3 into nuget.client, we are not taking Pull Requests at this point in this repo because dev is open for 3.2.1 fixes only. So its a good time to take a look at it and make a decision, but the PR itself will need to go somewhere else.

**Comment by yishaigalatzer** [comment]
@dsplaisted Based on our offline discussion, I believe this is not the right fix. Are we in agreement?

**Comment by dsplaisted** [comment]
@yishaigalatzer I will set up a meeting (probably next week) for us to discuss what we're trying to do and what the right way to do it is.

**Comment by yishaigalatzer** [comment]
@dsplaisted I'm closing this here, since we are no longer going to take PRs in this repo. All new work should go to nuget.client repo

**Pull request closed without merging**
