### PR TITLE
Wrap exceptions in NuGetProtocolException

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #371

[Review on Reviewable](https://reviewable.io/reviews/nuget/nuget3/23)

### CODE REVIEW

**Comment by emgarten** [comment]
This extra exception handling should happen around all resources, not just the new find by id resource.

For example the v3 service index resource needs to handle when the page returned is an XML error page, or invalid json.

**Comment by pranavkm** [comment]
Updated

**Comment by yishaigalatzer** [comment]
@pranavkm can this go in?

**Comment by pranavkm** [comment]
Already merged.

**Pull request closed without merging**
