### PR TITLE
Collapse default sources as part of SetDefaultPackageSources

### PR DESCRIPTION
**Pull request by pranavkm**
Part of https://github.com/NuGet/Home/issues/861

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @yishaigalatzer  \ @deepakaravindr  \ @zhili1208

**Comment by yishaigalatzer** [comment]
looks good, but I'm not familiar enough with this code to really sign off.

**Comment by zhili1208** [comment]
looks good for me

**Comment by pranavkm** [comment]
cc @danliu \ @emgarten, could you have a look?

**Comment by emgarten** [comment]
:shipit:

**Pull request closed without merging**
